  <!-- AFRICA -->
  <option<?php if($site['datetime']['timezone'] == 'Africa/Abidjan'){ ?> selected <?php } ?>>Africa/Abidjan</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Accra'){ ?> selected <?php } ?>>Africa/Accra</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Addis_Ababa'){ ?> selected <?php } ?>>Africa/Addis_Ababa</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Algiers'){ ?> selected <?php } ?>>Africa/Algiers</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Asmara'){ ?> selected <?php } ?>>Africa/Asmara</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Bamako'){ ?> selected <?php } ?>>Africa/Bamako</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Bangui'){ ?> selected <?php } ?>>Africa/Bangui</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Banjul'){ ?> selected <?php } ?>>Africa/Banjul</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Bissau'){ ?> selected <?php } ?>>Africa/Bissau</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Blantyre'){ ?> selected <?php } ?>>Africa/Blantyre</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Brazzaville'){ ?> selected <?php } ?>>Africa/Brazzaville</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Bujumbura'){ ?> selected <?php } ?>>Africa/Bujumbura</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Cairo'){ ?> selected <?php } ?>>Africa/Cairo</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Casablanca'){ ?> selected <?php } ?>>Africa/Casablanca</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Ceuta'){ ?> selected <?php } ?>>Africa/Ceuta</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Conakry'){ ?> selected <?php } ?>>Africa/Conakry</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Dakar'){ ?> selected <?php } ?>>Africa/Dakar</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Dar_es_Salaam'){ ?> selected <?php } ?>>Africa/Dar_es_Salaam</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Djibouti'){ ?> selected <?php } ?>>Africa/Djibouti</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Douala'){ ?> selected <?php } ?>>Africa/Douala</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/El_Aaiun'){ ?> selected <?php } ?>>Africa/El_Aaiun</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Freetown'){ ?> selected <?php } ?>>Africa/Freetown</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Gaborone'){ ?> selected <?php } ?>>Africa/Gaborone</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Harare'){ ?> selected <?php } ?>>Africa/Harare</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Johannesburg'){ ?> selected <?php } ?>>Africa/Johannesburg</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Juba'){ ?> selected <?php } ?>>Africa/Juba</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Kampala'){ ?> selected <?php } ?>>Africa/Kampala</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Khartoum'){ ?> selected <?php } ?>>Africa/Khartoum</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Kigali'){ ?> selected <?php } ?>>Africa/Kigali</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Kinshasa'){ ?> selected <?php } ?>>Africa/Kinshasa</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Lagos'){ ?> selected <?php } ?>>Africa/Lagos</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Libreville'){ ?> selected <?php } ?>>Africa/Libreville</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Lome'){ ?> selected <?php } ?>>Africa/Lome</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Luanda'){ ?> selected <?php } ?>>Africa/Luanda</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Lubumbashi'){ ?> selected <?php } ?>>Africa/Lubumbashi</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Lusaka'){ ?> selected <?php } ?>>Africa/Lusaka</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Malabo'){ ?> selected <?php } ?>>Africa/Malabo</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Maputo'){ ?> selected <?php } ?>>Africa/Maputo</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Maseru'){ ?> selected <?php } ?>>Africa/Maseru</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Mbabane'){ ?> selected <?php } ?>>Africa/Mbabane</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Mogadishu'){ ?> selected <?php } ?>>Africa/Mogadishu</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Monrovia'){ ?> selected <?php } ?>>Africa/Monrovia</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Nairobi'){ ?> selected <?php } ?>>Africa/Nairobi</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Ndjamena'){ ?> selected <?php } ?>>Africa/Ndjamena</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Niamey'){ ?> selected <?php } ?>>Africa/Niamey</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Nouakchott'){ ?> selected <?php } ?>>Africa/Nouakchott</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Ouagadougou'){ ?> selected <?php } ?>>Africa/Ouagadougou</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Porto-Novo'){ ?> selected <?php } ?>>Africa/Porto-Novo</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Sao_Tome'){ ?> selected <?php } ?>>Africa/Sao_Tome</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Tripoli'){ ?> selected <?php } ?>>Africa/Tripoli</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Tunis'){ ?> selected <?php } ?>>Africa/Tunis</option>
  <option<?php if($site['datetime']['timezone'] == 'Africa/Windhoek'){ ?> selected <?php } ?>>Africa/Windhoek</option>
  <!-- AMERICA -->
  <option<?php if($site['datetime']['timezone'] == 'America/Adak'){ ?> selected <?php } ?>>America/Adak</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Anchorage'){ ?> selected <?php } ?>>America/Anchorage</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Anguilla'){ ?> selected <?php } ?>>America/Anguilla</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Antigua'){ ?> selected <?php } ?>>America/Antigua</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Araguaina'){ ?> selected <?php } ?>>America/Araguaina</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Argentina/Buenos_Aires'){ ?> selected <?php } ?>>America/Argentina/Buenos_Aires</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Argentina/Catamarca'){ ?> selected <?php } ?>>America/Argentina/Catamarca</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Argentina/Cordoba'){ ?> selected <?php } ?>>America/Argentina/Cordoba</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Argentina/Jujuy'){ ?> selected <?php } ?>>America/Argentina/Jujuy</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Argentina/La_Rioja'){ ?> selected <?php } ?>>America/Argentina/La_Rioja</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Argentina/Mendoza'){ ?> selected <?php } ?>>America/Argentina/Mendoza</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Argentina/Rio_Gallegos'){ ?> selected <?php } ?>>America/Argentina/Rio_Gallegos</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Argentina/Salta'){ ?> selected <?php } ?>>America/Argentina/Salta</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Argentina/San_Juan'){ ?> selected <?php } ?>>America/Argentina/San_Juan</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Argentina/San_Luis'){ ?> selected <?php } ?>>America/Argentina/San_Luis</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Argentina/Tucuman'){ ?> selected <?php } ?>>America/Argentina/Tucuman</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Argentina/Ushuaia'){ ?> selected <?php } ?>>America/Argentina/Ushuaia</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Aruba'){ ?> selected <?php } ?>>America/Aruba</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Asuncion'){ ?> selected <?php } ?>>America/Asuncion</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Atikokan'){ ?> selected <?php } ?>>America/Atikokan</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Bahia'){ ?> selected <?php } ?>>America/Bahia</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Bahia_Banderas'){ ?> selected <?php } ?>>America/Bahia_Banderas</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Barbados'){ ?> selected <?php } ?>>America/Barbados</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Belem'){ ?> selected <?php } ?>>America/Belem</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Belize'){ ?> selected <?php } ?>>America/Belize</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Blanc-Sablon'){ ?> selected <?php } ?>>America/Blanc-Sablon</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Boa_Vista'){ ?> selected <?php } ?>>America/Boa_Vista</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Bogota'){ ?> selected <?php } ?>>America/Bogota</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Boise'){ ?> selected <?php } ?>>America/Boise</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Cambridge_Bay'){ ?> selected <?php } ?>>America/Cambridge_Bay</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Campo_Grande'){ ?> selected <?php } ?>>America/Campo_Grande</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Cancun'){ ?> selected <?php } ?>>America/Cancun</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Caracas'){ ?> selected <?php } ?>>America/Caracas</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Cayenne'){ ?> selected <?php } ?>>America/Cayenne</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Cayman'){ ?> selected <?php } ?>>America/Cayman</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Chicago'){ ?> selected <?php } ?>>America/Chicago</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Chihuahua'){ ?> selected <?php } ?>>America/Chihuahua</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Costa_Rica'){ ?> selected <?php } ?>>America/Costa_Rica</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Creston'){ ?> selected <?php } ?>>America/Creston</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Cuiaba'){ ?> selected <?php } ?>>America/Cuiaba</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Curacao'){ ?> selected <?php } ?>>America/Curacao</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Danmarkshavn'){ ?> selected <?php } ?>>America/Danmarkshavn</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Dawson'){ ?> selected <?php } ?>>America/Dawson</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Dawson_Creek'){ ?> selected <?php } ?>>America/Dawson_Creek</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Denver'){ ?> selected <?php } ?>>America/Denver</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Detroit'){ ?> selected <?php } ?>>America/Detroit</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Dominica'){ ?> selected <?php } ?>>America/Dominica</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Edmonton'){ ?> selected <?php } ?>>America/Edmonton</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Eirunepe'){ ?> selected <?php } ?>>America/Eirunepe</option>
  <option<?php if($site['datetime']['timezone'] == 'America/El_Salvador'){ ?> selected <?php } ?>>America/El_Salvador</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Fort_Nelson'){ ?> selected <?php } ?>>America/Fort_Nelson</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Fortaleza'){ ?> selected <?php } ?>>America/Fortaleza</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Glace_Bay'){ ?> selected <?php } ?>>America/Glace_Bay</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Godthab'){ ?> selected <?php } ?>>America/Godthab</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Goose_Bay'){ ?> selected <?php } ?>>America/Goose_Bay</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Grand_Turk'){ ?> selected <?php } ?>>America/Grand_Turk</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Grenada'){ ?> selected <?php } ?>>America/Grenada</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Guadeloupe'){ ?> selected <?php } ?>>America/Guadeloupe</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Guatemala'){ ?> selected <?php } ?>>America/Guatemala</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Guayaquil'){ ?> selected <?php } ?>>America/Guayaquil</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Guyana'){ ?> selected <?php } ?>>America/Guyana</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Halifax'){ ?> selected <?php } ?>>America/Halifax</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Havana'){ ?> selected <?php } ?>>America/Havana</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Hermosillo'){ ?> selected <?php } ?>>America/Hermosillo</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Indiana/Indianapolis'){ ?> selected <?php } ?>>America/Indiana/Indianapolis</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Indiana/Knox'){ ?> selected <?php } ?>>America/Indiana/Knox</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Indiana/Marengo'){ ?> selected <?php } ?>>America/Indiana/Marengo</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Indiana/Petersburg'){ ?> selected <?php } ?>>America/Indiana/Petersburg</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Indiana/Tell_City'){ ?> selected <?php } ?>>America/Indiana/Tell_City</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Indiana/Vevay'){ ?> selected <?php } ?>>America/Indiana/Vevay</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Indiana/Vincennes'){ ?> selected <?php } ?>>America/Indiana/Vincennes</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Indiana/Winamac'){ ?> selected <?php } ?>>America/Indiana/Winamac</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Inuvik'){ ?> selected <?php } ?>>America/Inuvik</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Iqaluit'){ ?> selected <?php } ?>>America/Iqaluit</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Jamaica'){ ?> selected <?php } ?>>America/Jamaica</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Juneau'){ ?> selected <?php } ?>>America/Juneau</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Kentucky/Louisville'){ ?> selected <?php } ?>>America/Kentucky/Louisville</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Kentucky/Monticello'){ ?> selected <?php } ?>>America/Kentucky/Monticello</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Kralendijk'){ ?> selected <?php } ?>>America/Kralendijk</option>
  <option<?php if($site['datetime']['timezone'] == 'America/La_Paz'){ ?> selected <?php } ?>>America/La_Paz</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Lima'){ ?> selected <?php } ?>>America/Lima</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Los_Angeles'){ ?> selected <?php } ?>>America/Los_Angeles</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Lower_Princes'){ ?> selected <?php } ?>>America/Lower_Princes</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Maceio'){ ?> selected <?php } ?>>America/Maceio</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Managua'){ ?> selected <?php } ?>>America/Managua</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Manaus'){ ?> selected <?php } ?>>America/Manaus</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Marigot'){ ?> selected <?php } ?>>America/Marigot</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Martinique'){ ?> selected <?php } ?>>America/Martinique</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Matamoros'){ ?> selected <?php } ?>>America/Matamoros</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Mazatlan'){ ?> selected <?php } ?>>America/Mazatlan</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Menominee'){ ?> selected <?php } ?>>America/Menominee</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Merida'){ ?> selected <?php } ?>>America/Merida</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Metlakatla'){ ?> selected <?php } ?>>America/Metlakatla</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Mexico_City'){ ?> selected <?php } ?>>America/Mexico_City</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Miquelon'){ ?> selected <?php } ?>>America/Miquelon</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Moncton'){ ?> selected <?php } ?>>America/Moncton</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Monterrey'){ ?> selected <?php } ?>>America/Monterrey</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Montevideo'){ ?> selected <?php } ?>>America/Montevideo</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Montserrat'){ ?> selected <?php } ?>>America/Montserrat</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Nassau'){ ?> selected <?php } ?>>America/Nassau</option>
  <option<?php if($site['datetime']['timezone'] == 'America/New_York'){ ?> selected <?php } ?>>America/New_York</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Nipigon'){ ?> selected <?php } ?>>America/Nipigon</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Nome'){ ?> selected <?php } ?>>America/Nome</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Noronha'){ ?> selected <?php } ?>>America/Noronha</option>
  <option<?php if($site['datetime']['timezone'] == 'America/North_Dakota/Beulah'){ ?> selected <?php } ?>>America/North_Dakota/Beulah</option>
  <option<?php if($site['datetime']['timezone'] == 'America/North_Dakota/Center'){ ?> selected <?php } ?>>America/North_Dakota/Center</option>
  <option<?php if($site['datetime']['timezone'] == 'America/North_Dakota/New_Salem'){ ?> selected <?php } ?>>America/North_Dakota/New_Salem</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Ojinaga'){ ?> selected <?php } ?>>America/Ojinaga</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Panama'){ ?> selected <?php } ?>>America/Panama</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Pangnirtung'){ ?> selected <?php } ?>>America/Pangnirtung</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Paramaribo'){ ?> selected <?php } ?>>America/Paramaribo</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Phoenix'){ ?> selected <?php } ?>>America/Phoenix</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Port-au-Prince'){ ?> selected <?php } ?>>America/Port-au-Prince</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Port_of_Spain'){ ?> selected <?php } ?>>America/Port_of_Spain</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Porto_Velho'){ ?> selected <?php } ?>>America/Porto_Velho</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Puerto_Rico'){ ?> selected <?php } ?>>America/Puerto_Rico</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Punta_Arenas'){ ?> selected <?php } ?>>America/Punta_Arenas</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Rainy_River'){ ?> selected <?php } ?>>America/Rainy_River</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Rankin_Inlet'){ ?> selected <?php } ?>>America/Rankin_Inlet</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Recife'){ ?> selected <?php } ?>>America/Recife</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Regina'){ ?> selected <?php } ?>>America/Regina</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Resolute'){ ?> selected <?php } ?>>America/Resolute</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Rio_Branco'){ ?> selected <?php } ?>>America/Rio_Branco</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Santarem'){ ?> selected <?php } ?>>America/Santarem</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Santiago'){ ?> selected <?php } ?>>America/Santiago</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Santo_Domingo'){ ?> selected <?php } ?>>America/Santo_Domingo</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Sao_Paulo'){ ?> selected <?php } ?>>America/Sao_Paulo</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Scoresbysund'){ ?> selected <?php } ?>>America/Scoresbysund</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Sitka'){ ?> selected <?php } ?>>America/Sitka</option>
  <option<?php if($site['datetime']['timezone'] == 'America/St_Barthelemy'){ ?> selected <?php } ?>>America/St_Barthelemy</option>
  <option<?php if($site['datetime']['timezone'] == 'America/St_Johns'){ ?> selected <?php } ?>>America/St_Johns</option>
  <option<?php if($site['datetime']['timezone'] == 'America/St_Kitts'){ ?> selected <?php } ?>>America/St_Kitts</option>
  <option<?php if($site['datetime']['timezone'] == 'America/St_Lucia'){ ?> selected <?php } ?>>America/St_Lucia</option>
  <option<?php if($site['datetime']['timezone'] == 'America/St_Thomas'){ ?> selected <?php } ?>>America/St_Thomas</option>
  <option<?php if($site['datetime']['timezone'] == 'America/St_Vincent'){ ?> selected <?php } ?>>America/St_Vincent</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Swift_Current'){ ?> selected <?php } ?>>America/Swift_Current</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Tegucigalpa'){ ?> selected <?php } ?>>America/Tegucigalpa</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Thule'){ ?> selected <?php } ?>>America/Thule</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Thunder_Bay'){ ?> selected <?php } ?>>America/Thunder_Bay</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Tijuana'){ ?> selected <?php } ?>>America/Tijuana</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Toronto'){ ?> selected <?php } ?>>America/Toronto</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Tortola'){ ?> selected <?php } ?>>America/Tortola</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Vancouver'){ ?> selected <?php } ?>>America/Vancouver</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Whitehorse'){ ?> selected <?php } ?>>America/Whitehorse</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Winnipeg'){ ?> selected <?php } ?>>America/Winnipeg</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Yakutat'){ ?> selected <?php } ?>>America/Yakutat</option>
  <option<?php if($site['datetime']['timezone'] == 'America/Yellowknife'){ ?> selected <?php } ?>>America/Yellowknife</option>
  <option<?php if($site['datetime']['timezone'] == 'Antarctica/Casey'){ ?> selected <?php } ?>>Antarctica/Casey</option>
  <option<?php if($site['datetime']['timezone'] == 'Antarctica/Davis'){ ?> selected <?php } ?>>Antarctica/Davis</option>
  <option<?php if($site['datetime']['timezone'] == 'Antarctica/DumontDUrville'){ ?> selected <?php } ?>>Antarctica/DumontDUrville</option>
  <option<?php if($site['datetime']['timezone'] == 'Antarctica/Macquarie'){ ?> selected <?php } ?>>Antarctica/Macquarie</option>
  <option<?php if($site['datetime']['timezone'] == 'Antarctica/Mawson'){ ?> selected <?php } ?>>Antarctica/Mawson</option>
  <option<?php if($site['datetime']['timezone'] == 'Antarctica/McMurdo'){ ?> selected <?php } ?>>Antarctica/McMurdo</option>
  <option<?php if($site['datetime']['timezone'] == 'Antarctica/Palmer'){ ?> selected <?php } ?>>Antarctica/Palmer</option>
  <option<?php if($site['datetime']['timezone'] == 'Antarctica/Rothera'){ ?> selected <?php } ?>>Antarctica/Rothera</option>
  <option<?php if($site['datetime']['timezone'] == 'Antarctica/Syowa'){ ?> selected <?php } ?>>Antarctica/Syowa</option>
  <option<?php if($site['datetime']['timezone'] == 'Antarctica/Troll'){ ?> selected <?php } ?>>Antarctica/Troll</option>
  <option<?php if($site['datetime']['timezone'] == 'Antarctica/Vostok'){ ?> selected <?php } ?>>Antarctica/Vostok</option>
  <option<?php if($site['datetime']['timezone'] == 'Arctic/Longyearbyen'){ ?> selected <?php } ?>>Arctic/Longyearbyen</option>
  <!-- ASIA -->
  <option<?php if($site['datetime']['timezone'] == 'Asia/Aden'){ ?> selected <?php } ?>>Asia/Aden</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Almaty'){ ?> selected <?php } ?>>Asia/Almaty</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Amman'){ ?> selected <?php } ?>>Asia/Amman</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Anadyr'){ ?> selected <?php } ?>>Asia/Anadyr</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Aqtau'){ ?> selected <?php } ?>>Asia/Aqtau</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Aqtobe'){ ?> selected <?php } ?>>Asia/Aqtobe</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Ashgabat'){ ?> selected <?php } ?>>Asia/Ashgabat</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Atyrau'){ ?> selected <?php } ?>>Asia/Atyrau</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Baghdad'){ ?> selected <?php } ?>>Asia/Baghdad</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Bahrain'){ ?> selected <?php } ?>>Asia/Bahrain</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Baku'){ ?> selected <?php } ?>>Asia/Baku</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Bangkok'){ ?> selected <?php } ?>>Asia/Bangkok</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Barnaul'){ ?> selected <?php } ?>>Asia/Barnaul</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Beirut'){ ?> selected <?php } ?>>Asia/Beirut</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Bishkek'){ ?> selected <?php } ?>>Asia/Bishkek</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Brunei'){ ?> selected <?php } ?>>Asia/Brunei</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Chita'){ ?> selected <?php } ?>>Asia/Chita</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Choibalsan'){ ?> selected <?php } ?>>Asia/Choibalsan</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Colombo'){ ?> selected <?php } ?>>Asia/Colombo</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Damascus'){ ?> selected <?php } ?>>Asia/Damascus</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Dhaka'){ ?> selected <?php } ?>>Asia/Dhaka</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Dili'){ ?> selected <?php } ?>>Asia/Dili</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Dubai'){ ?> selected <?php } ?>>Asia/Dubai</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Dushanbe'){ ?> selected <?php } ?>>Asia/Dushanbe</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Famagusta'){ ?> selected <?php } ?>>Asia/Famagusta</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Gaza'){ ?> selected <?php } ?>>Asia/Gaza</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Hebron'){ ?> selected <?php } ?>>Asia/Hebron</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Ho_Chi_Minh'){ ?> selected <?php } ?>>Asia/Ho_Chi_Minh</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Hong_Kong'){ ?> selected <?php } ?>>Asia/Hong_Kong</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Hovd'){ ?> selected <?php } ?>>Asia/Hovd</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Irkutsk'){ ?> selected <?php } ?>>Asia/Irkutsk</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Jakarta'){ ?> selected <?php } ?>>Asia/Jakarta</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Jayapura'){ ?> selected <?php } ?>>Asia/Jayapura</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Jerusalem'){ ?> selected <?php } ?>>Asia/Jerusalem</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Kabul'){ ?> selected <?php } ?>>Asia/Kabul</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Kamchatka'){ ?> selected <?php } ?>>Asia/Kamchatka</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Karachi'){ ?> selected <?php } ?>>Asia/Karachi</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Kathmandu'){ ?> selected <?php } ?>>Asia/Kathmandu</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Khandyga'){ ?> selected <?php } ?>>Asia/Khandyga</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Kolkata'){ ?> selected <?php } ?>>Asia/Kolkata</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Krasnoyarsk'){ ?> selected <?php } ?>>Asia/Krasnoyarsk</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Kuala_Lumpur'){ ?> selected <?php } ?>>Asia/Kuala_Lumpur</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Kuching'){ ?> selected <?php } ?>>Asia/Kuching</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Kuwait'){ ?> selected <?php } ?>>Asia/Kuwait</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Macau'){ ?> selected <?php } ?>>Asia/Macau</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Magadan'){ ?> selected <?php } ?>>Asia/Magadan</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Makassar'){ ?> selected <?php } ?>>Asia/Makassar</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Manila'){ ?> selected <?php } ?>>Asia/Manila</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Muscat'){ ?> selected <?php } ?>>Asia/Muscat</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Nicosia'){ ?> selected <?php } ?>>Asia/Nicosia</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Novokuznetsk'){ ?> selected <?php } ?>>Asia/Novokuznetsk</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Novosibirsk'){ ?> selected <?php } ?>>Asia/Novosibirsk</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Omsk'){ ?> selected <?php } ?>>Asia/Omsk</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Oral'){ ?> selected <?php } ?>>Asia/Oral</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Phnom_Penh'){ ?> selected <?php } ?>>Asia/Phnom_Penh</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Pontianak'){ ?> selected <?php } ?>>Asia/Pontianak</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Pyongyang'){ ?> selected <?php } ?>>Asia/Pyongyang</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Qatar'){ ?> selected <?php } ?>>Asia/Qatar</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Qostanay'){ ?> selected <?php } ?>>Asia/Qostanay</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Qyzylorda'){ ?> selected <?php } ?>>Asia/Qyzylorda</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Riyadh'){ ?> selected <?php } ?>>Asia/Riyadh</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Sakhalin'){ ?> selected <?php } ?>>Asia/Sakhalin</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Samarkand'){ ?> selected <?php } ?>>Asia/Samarkand</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Seoul'){ ?> selected <?php } ?>>Asia/Seoul</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Shanghai'){ ?> selected <?php } ?>>Asia/Shanghai</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Singapore'){ ?> selected <?php } ?>>Asia/Singapore</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Srednekolymsk'){ ?> selected <?php } ?>>Asia/Srednekolymsk</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Taipei'){ ?> selected <?php } ?>>Asia/Taipei</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Tashkent'){ ?> selected <?php } ?>>Asia/Tashkent</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Tbilisi'){ ?> selected <?php } ?>>Asia/Tbilisi</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Tehran'){ ?> selected <?php } ?>>Asia/Tehran</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Thimphu'){ ?> selected <?php } ?>>Asia/Thimphu</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Tokyo'){ ?> selected <?php } ?>>Asia/Tokyo</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Tomsk'){ ?> selected <?php } ?>>Asia/Tomsk</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Ulaanbaatar'){ ?> selected <?php } ?>>Asia/Ulaanbaatar</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Urumqi'){ ?> selected <?php } ?>>Asia/Urumqi</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Ust-Nera'){ ?> selected <?php } ?>>Asia/Ust-Nera</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Vientiane'){ ?> selected <?php } ?>>Asia/Vientiane</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Vladivostok'){ ?> selected <?php } ?>>Asia/Vladivostok</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Yakutsk'){ ?> selected <?php } ?>>Asia/Yakutsk</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Yangon'){ ?> selected <?php } ?>>Asia/Yangon</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Yekaterinburg'){ ?> selected <?php } ?>>Asia/Yekaterinburg</option>
  <option<?php if($site['datetime']['timezone'] == 'Asia/Yerevan'){ ?> selected <?php } ?>>Asia/Yerevan</option>
  <!-- ATLANTIC -->
  <option<?php if($site['datetime']['timezone'] == 'Atlantic/Azores'){ ?> selected <?php } ?>>Atlantic/Azores</option>
  <option<?php if($site['datetime']['timezone'] == 'Atlantic/Bermuda'){ ?> selected <?php } ?>>Atlantic/Bermuda</option>
  <option<?php if($site['datetime']['timezone'] == 'Atlantic/Canary'){ ?> selected <?php } ?>>Atlantic/Canary</option>
  <option<?php if($site['datetime']['timezone'] == 'Atlantic/Cape_Verde'){ ?> selected <?php } ?>>Atlantic/Cape_Verde</option>
  <option<?php if($site['datetime']['timezone'] == 'Atlantic/Faroe'){ ?> selected <?php } ?>>Atlantic/Faroe</option>
  <option<?php if($site['datetime']['timezone'] == 'Atlantic/Madeira'){ ?> selected <?php } ?>>Atlantic/Madeira</option>
  <option<?php if($site['datetime']['timezone'] == 'Atlantic/Reykjavik'){ ?> selected <?php } ?>>Atlantic/Reykjavik</option>
  <option<?php if($site['datetime']['timezone'] == 'Atlantic/South_Georgia'){ ?> selected <?php } ?>>Atlantic/South_Georgia</option>
  <option<?php if($site['datetime']['timezone'] == 'Atlantic/St_Helena'){ ?> selected <?php } ?>>Atlantic/St_Helena</option>
  <option<?php if($site['datetime']['timezone'] == 'Atlantic/Stanley'){ ?> selected <?php } ?>>Atlantic/Stanley</option>
  <!-- AUSTRALIA -->
  <option<?php if($site['datetime']['timezone'] == 'Australia/Adelaide'){ ?> selected <?php } ?>>Australia/Adelaide</option>
  <option<?php if($site['datetime']['timezone'] == 'Australia/Brisbane'){ ?> selected <?php } ?>>Australia/Brisbane</option>
  <option<?php if($site['datetime']['timezone'] == 'Australia/Broken_Hill'){ ?> selected <?php } ?>>Australia/Broken_Hill</option>
  <option<?php if($site['datetime']['timezone'] == 'Australia/Currie'){ ?> selected <?php } ?>>Australia/Currie</option>
  <option<?php if($site['datetime']['timezone'] == 'Australia/Darwin'){ ?> selected <?php } ?>>Australia/Darwin</option>
  <option<?php if($site['datetime']['timezone'] == 'Australia/Eucla'){ ?> selected <?php } ?>>Australia/Eucla</option>
  <option<?php if($site['datetime']['timezone'] == 'Australia/Hobart'){ ?> selected <?php } ?>>Australia/Hobart</option>
  <option<?php if($site['datetime']['timezone'] == 'Australia/Lindeman'){ ?> selected <?php } ?>>Australia/Lindeman</option>
  <option<?php if($site['datetime']['timezone'] == 'Australia/Lindeman'){ ?> selected <?php } ?>>Australia/Lindeman</option>
  <option<?php if($site['datetime']['timezone'] == 'Australia/Melbourne'){ ?> selected <?php } ?>>Australia/Melbourne</option>
  <option<?php if($site['datetime']['timezone'] == 'Australia/Perth'){ ?> selected <?php } ?>>Australia/Perth</option>
  <option<?php if($site['datetime']['timezone'] == 'Australia/Sydney'){ ?> selected <?php } ?>>Australia/Sydney</option>
  <!-- EUROPA -->
  <option<?php if($site['datetime']['timezone'] == 'Europe/Amsterdam'){ ?> selected <?php } ?>>Europe/Amsterdam</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Andorra'){ ?> selected <?php } ?>>Europe/Andorra</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Astrakhan'){ ?> selected <?php } ?>>Europe/Astrakhan</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Athens'){ ?> selected <?php } ?>>Europe/Athens</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Belgrade'){ ?> selected <?php } ?>>Europe/Belgrade</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Berlin'){ ?> selected <?php } ?>>Europe/Berlin</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Bratislava'){ ?> selected <?php } ?>>Europe/Bratislava</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Brussels'){ ?> selected <?php } ?>>Europe/Brussels</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Bucharest'){ ?> selected <?php } ?>>Europe/Bucharest</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Budapest'){ ?> selected <?php } ?>>Europe/Budapest</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Busingen'){ ?> selected <?php } ?>>Europe/Busingen</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Chisinau'){ ?> selected <?php } ?>>Europe/Chisinau</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Copenhagen'){ ?> selected <?php } ?>>Europe/Copenhagen</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Dublin'){ ?> selected <?php } ?>>Europe/Dublin</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Gibraltar'){ ?> selected <?php } ?>>Europe/Gibraltar</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Guernsey'){ ?> selected <?php } ?>>Europe/Guernsey</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Helsinki'){ ?> selected <?php } ?>>Europe/Helsinki</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Isle_of_Man'){ ?> selected <?php } ?>>Europe/Isle_of_Man</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Istanbul'){ ?> selected <?php } ?>>Europe/Istanbul</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Jersey'){ ?> selected <?php } ?>>Europe/Jersey</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Kaliningrad'){ ?> selected <?php } ?>>Europe/Kaliningrad</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Kiev'){ ?> selected <?php } ?>>Europe/Kiev</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Kirov'){ ?> selected <?php } ?>>Europe/Kirov</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Lisbon'){ ?> selected <?php } ?>>Europe/Lisbon</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Ljubljana'){ ?> selected <?php } ?>>Europe/Ljubljana</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/London'){ ?> selected <?php } ?>>Europe/London</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Luxembourg'){ ?> selected <?php } ?>>Europe/Luxembourg</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Madrid'){ ?> selected <?php } ?>>Europe/Madrid</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Malta'){ ?> selected <?php } ?>>Europe/Malta</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Mariehamn'){ ?> selected <?php } ?>>Europe/Mariehamn</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Minsk'){ ?> selected <?php } ?>>Europe/Minsk</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Monaco'){ ?> selected <?php } ?>>Europe/Monaco</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Moscow'){ ?> selected <?php } ?>>Europe/Moscow</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Oslo'){ ?> selected <?php } ?>>Europe/Oslo</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Paris'){ ?> selected <?php } ?>>Europe/Paris</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Podgorica'){ ?> selected <?php } ?>>Europe/Podgorica</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Prague'){ ?> selected <?php } ?>>Europe/Prague</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Riga'){ ?> selected <?php } ?>>Europe/Riga</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Rome'){ ?> selected <?php } ?>>Europe/Rome</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Samara'){ ?> selected <?php } ?>>Europe/Samara</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/San_Marino'){ ?> selected <?php } ?>>Europe/San_Marino</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Sarajevo'){ ?> selected <?php } ?>>Europe/Sarajevo</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Saratov'){ ?> selected <?php } ?>>Europe/Saratov</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Simferopol'){ ?> selected <?php } ?>>Europe/Simferopol</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Skopje'){ ?> selected <?php } ?>>Europe/Skopje</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Sofia'){ ?> selected <?php } ?>>Europe/Sofia</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Stockholm'){ ?> selected <?php } ?>>Europe/Stockholm</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Tallinn'){ ?> selected <?php } ?>>Europe/Tallinn</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Tirane'){ ?> selected <?php } ?>>Europe/Tirane</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Ulyanovsk'){ ?> selected <?php } ?>>Europe/Ulyanovsk</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Uzhgorod'){ ?> selected <?php } ?>>Europe/Uzhgorod</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Vaduz'){ ?> selected <?php } ?>>Europe/Vaduz</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Vatican'){ ?> selected <?php } ?>>Europe/Vatican</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Vienna'){ ?> selected <?php } ?>>Europe/Vienna</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Vilnius'){ ?> selected <?php } ?>>Europe/Vilnius</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Volgograd'){ ?> selected <?php } ?>>Europe/Volgograd</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Warsaw'){ ?> selected <?php } ?>>Europe/Warsaw</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Zagreb'){ ?> selected <?php } ?>>Europe/Zagreb</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Zaporozhye'){ ?> selected <?php } ?>>Europe/Zaporozhye</option>
  <option<?php if($site['datetime']['timezone'] == 'Europe/Zurich'){ ?> selected <?php } ?>>Europe/Zurich</option>
  <!-- INDIA -->
  <option<?php if($site['datetime']['timezone'] == 'Indian/Antananarivo'){ ?> selected <?php } ?>>Indian/Antananarivo</option>
  <option<?php if($site['datetime']['timezone'] == 'Indian/Chagos'){ ?> selected <?php } ?>>Indian/Chagos</option>
  <option<?php if($site['datetime']['timezone'] == 'Indian/Christmas'){ ?> selected <?php } ?>>Indian/Christmas</option>
  <option<?php if($site['datetime']['timezone'] == 'Indian/Cocos'){ ?> selected <?php } ?>>Indian/Cocos</option>
  <option<?php if($site['datetime']['timezone'] == 'Indian/Comoro'){ ?> selected <?php } ?>>Indian/Comoro</option>
  <option<?php if($site['datetime']['timezone'] == 'Indian/Kerguelen'){ ?> selected <?php } ?>>Indian/Kerguelen</option>
  <option<?php if($site['datetime']['timezone'] == 'Indian/Mahe'){ ?> selected <?php } ?>>Indian/Mahe</option>
  <option<?php if($site['datetime']['timezone'] == 'Indian/Maldives'){ ?> selected <?php } ?>>Indian/Maldives</option>
  <option<?php if($site['datetime']['timezone'] == 'Indian/Mauritius'){ ?> selected <?php } ?>>Indian/Mauritius</option>
  <option<?php if($site['datetime']['timezone'] == 'Indian/Mayotte'){ ?> selected <?php } ?>>Indian/Mayotte</option>
  <option<?php if($site['datetime']['timezone'] == 'Indian/Reunion'){ ?> selected <?php } ?>>Indian/Reunion</option>
  <!-- PACIFIC -->
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Apia'){ ?> selected <?php } ?>>Pacific/Apia</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Auckland'){ ?> selected <?php } ?>>Pacific/Auckland</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Bougainville'){ ?> selected <?php } ?>>Pacific/Bougainville</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Chatham'){ ?> selected <?php } ?>>Pacific/Chatham</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Chuuk'){ ?> selected <?php } ?>>Pacific/Chuuk</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Easter'){ ?> selected <?php } ?>>Pacific/Easter</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Efate'){ ?> selected <?php } ?>>Pacific/Efate</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Enderbury'){ ?> selected <?php } ?>>Pacific/Enderbury</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Fakaofo'){ ?> selected <?php } ?>>Pacific/Fakaofo</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Fiji'){ ?> selected <?php } ?>>Pacific/Fiji</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Funafuti'){ ?> selected <?php } ?>>Pacific/Funafuti</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Galapagos'){ ?> selected <?php } ?>>Pacific/Galapagos</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Gambier'){ ?> selected <?php } ?>>Pacific/Gambier</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Guadalcanal'){ ?> selected <?php } ?>>Pacific/Guadalcanal</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Guam'){ ?> selected <?php } ?>>Pacific/Guam</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Honolulu'){ ?> selected <?php } ?>>Pacific/Honolulu</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Kiritimati'){ ?> selected <?php } ?>>Pacific/Kiritimati</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Kosrae'){ ?> selected <?php } ?>>Pacific/Kosrae</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Kwajalein'){ ?> selected <?php } ?>>Pacific/Kwajalein</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Majuro'){ ?> selected <?php } ?>>Pacific/Majuro</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Marquesas'){ ?> selected <?php } ?>>Pacific/Marquesas</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Midway'){ ?> selected <?php } ?>>Pacific/Midway</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Nauru'){ ?> selected <?php } ?>>Pacific/Nauru</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Niue'){ ?> selected <?php } ?>>Pacific/Niue</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Norfolk'){ ?> selected <?php } ?>>Pacific/Norfolk</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Noumea'){ ?> selected <?php } ?>>Pacific/Noumea</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Pago_Pago'){ ?> selected <?php } ?>>Pacific/Pago_Pago</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Palau'){ ?> selected <?php } ?>>Pacific/Palau</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Pitcairn'){ ?> selected <?php } ?>>Pacific/Pitcairn</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Pohnpei'){ ?> selected <?php } ?>>Pacific/Pohnpei</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Port_Moresby'){ ?> selected <?php } ?>>Pacific/Port_Moresby</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Rarotonga'){ ?> selected <?php } ?>>Pacific/Rarotonga</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Saipan'){ ?> selected <?php } ?>>Pacific/Saipan</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Tahiti'){ ?> selected <?php } ?>>Pacific/Tahiti</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Tarawa'){ ?> selected <?php } ?>>Pacific/Tarawa</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Tongatapu'){ ?> selected <?php } ?>>Pacific/Tongatapu</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Wake'){ ?> selected <?php } ?>>Pacific/Wake</option>
  <option<?php if($site['datetime']['timezone'] == 'Pacific/Wallis'){ ?> selected <?php } ?>>Pacific/Wallis</option>
  <!----> 